### ISSUE TITLE
Export from bigquery using gzip in GCS

### ISSUE THREAD

**Issue by srisys** [GoogleCloudDataproc/hadoop-connectors#102]
HI,

Is there any option to provide export in gzip format for big query table when writing into temp GCS storage.?

**Comment by medb** [comment]
BigQuery export API [has](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#configuration.extract.compression) `configuration.extract.compression` property that accepts `GZIP` value.

I will need to take a look if/how it's wired in BigQuery connector though.
