### ISSUE TITLE
Conversion from InputStream -> ByteBuffer on gRPC writes creates many byte[] allocations.

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudDataproc/hadoop-connectors#1123]
Hi team, 

Investigating memory usage in the write path for gRPC; I found that significant allocations are coming from converting [InputStream -> ByteBuffer code](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/453b2f6099551d059ae8ee2d73e518f2c1e2ec8c/gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageClientWriteChannel.java#L129-L135) in the GCS connector: https://storage.googleapis.com/anima-frank/large-writes-grpc/grpc_100_write_100MiB_t_4_profile.html

Note: Workload runs Fsbenchmark uploading 10k 100MiB object across 4 threads in n2-standard-4 GCE using DirectPath.

~72% of allocations come from converting InputStream -> ByteBuffer creates 2 2MiB byte[]'s for every write:
- [ByteString.readFrom](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/453b2f6099551d059ae8ee2d73e518f2c1e2ec8c/gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageClientWriteChannel.java#L130): ~55% - creates a 2MiB byte[]
- [ByteString.toByteArray()](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/453b2f6099551d059ae8ee2d73e518f2c1e2ec8c/gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageClientWriteChannel.java#L135): ~18% - creates a 2MiB byte[]

Separately, java-storage does contribute to 19% of allocations, I'm digging into this as well. My current suspicion is that java-storage creates a buffer per upload and not per message.

**Comment by frankyn** [comment]
Update: I attempted to make a change to the code to workaround this issue but overall wall time is not suitable:
For a sequential write of 10k 100MiB objects; existing implementation is takes around ~2+ hours using gRPC DP while my prototype version is still running after ~9+ hours. 

@arunkumarchacko could you investigate alternatives?

cc: @schannahalli, @danielduhh

**Comment by arunkumarchacko** [comment]
This issue is fixed once we moved away from pipe.
