### ISSUE TITLE
globStatus call runs very slowly from Hadoop to GCS compared with gsutil

### ISSUE THREAD

**Issue by yzhou2001** [GoogleCloudDataproc/hadoop-connectors#123]
Run a glob listing on a big tree of around 890K entries.

1. Using Hadoop:
   ```bash
   hadoop fs -ls gs://bucketabc/1???/1/1/small-1.txt
   ```
   takes  3+ minutes;

2. Using Spark
   ```scala
   spark.read.format("com.databricks.spark.csv")
       .option("header", "false").option("delimiter", "\t").option("inferSchema", "true").option("mode", "DROPMALFORMED")
       .load("gs://bucketabc/1???/1/1/small-1.txt")
   ```
   takes 7+ minutes

3. While gsutil:
   ```bash
   gsutil ls gs://bucketabc/1???/1/1/small-1.txt
   ```
   only takes 8 seconds. 

It turns out that the full glob pattern has not been pushed down to GCS by the GCS connector. 

This problem could have significant impact on queries on data sets with huge number of partitions for either query performance consideration and/or as result of huge number of distributed processing tasks like MR and Spark.

A simple prototype fix has been observed to be able to close the significant perf gap.

**Comment by medb** [comment]
We need to address globbing performance in 2 phases:
1. run default glob and flat glob algorithms concurrently and return result as soon as one finishes.
2. parallelize flat glob algorithm implementation in the same way as gsutil [does it](https://github.com/GoogleCloudPlatform/bigdata-interop/issues/123#issuecomment-420458838).
