### ISSUE TITLE
Suggestion: would you use Guava targeting Java 7 runtime?

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudDataproc/hadoop-connectors#307]
Guava has 2 variations

- "-android" for Java 7
- "-jre" for Java 8

Our static analysis tool detected that `com.google.cloud.bigdataoss:gcsio:2.0.0` uses Guava's API that is only available in Java 8.

https://gist.github.com/suztomo/7c106278d974da8f0fc18b53ebcf47c4

```
(guava-28.2-android.jar) com.google.common.cache.CacheBuilder's method expireAfterWrite(java.time.Duration arg1) is not found
  referenced by
    ClassFile{jar=/.../bigdataoss/gcsio/2.0.0/gcsio-2.0.0.jar, className=com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl}
```

GCP users will face less `NoSuchMethodError`s if gcsio uses Guava with "-android" version. Would you use Guava with "-android" version?

# Google-cloud-java
[Google Cloud Java](https://github.com/googleapis/google-cloud-java) says

> Java 7 or above is required for using the clients in this repository.

# Out of scope
Note that this issue is not intended to change JDK version of this project.

**Comment by medb** [comment]
Thanks for suggestion, but it seems like a wrong solution for the problem at hand:
1. I don't think that Java 7 usage is wide-spread on GCP.
2. If you will override Guava version in your project to use `-jre` Guava flavor, will it fix analyzer warning?

**Comment by suztomo** [comment]
1. I don't have the number to determine that.

2. That is correct. However, it would defy google-cloud-java's Java 7 support.

**Comment by medb** [comment]
I think that version supported by `google-cloud-java` shouldn't matter here, because Beam [supports](https://beam.apache.org/get-started/quickstart-java/#set-up-your-development-environment) only Java 8?

**Comment by suztomo** [comment]
As long as Guava “-jre” is in the class path, there’s no problem. However, when a user’s project depends on google-cloud-java and gcsio (the order matters), the class path may get Guava “-android”, which is incompatible with current gcsio. Beam’s dependency static analysis above is an example that the build system picked Guava “-android”.

**Comment by medb** [comment]
The problem is that we already depend on functionality that is available only in Guava "-jre", that's why we cannot switch to Guava `-android` flavor.
