### ISSUE TITLE
Writing to GCS prefix requires permissions in parent "directories" of the bucket

### ISSUE THREAD

**Issue by simonvanderveldt** [GoogleCloudDataproc/hadoop-connectors#356]
When writing to GCS from Spark using this library to for example `gs://somebucket/prefix1/prefix2/prefix3` it seems like either Spark or this library is trying to create the parent "directories" first.

We limit write access of our Spark applications to a prefix that's specific to the Spark application so they only have access to objects that start with their full prefix (the role binding for `roles/storage.admin` uses `resource.name.startsWith('projects/_/buckets/projectname/objects/prefix1/prefix2/prefix3/` as its condition).

We get the following errors:
```
serviceaccount@projectname.iam.gserviceaccount.com does not have storage.objects.create access to somebucket/prefix1/prefix2/."
serviceaccount@projectname.iam.gserviceaccount.com does not have storage.objects.create access to somebucket/prefix1/."
```
So it seems like either Spark or this library is treating GCS like a regular filesystem and trying to create directories first before writing the data which is obviously not the correct behavior.
Is this something that can be fixed?

**Comment by medb** [comment]
What GCS connector version do you use?

**Comment by simonvanderveldt** [comment]
We're currently using `gcs-connector-hadoop2-2.0.1.jar`, I didn't see any changes that seemed related to this in the release notes.

**Comment by hongyegong** [comment]
I assume /prefix1/prefix2 doesn't exist beforehand, GCS connector itself in this case won't create nonexistent parent folder, this behavior is consistent with HDFS. 

If you still see the error, try:
1. check the condition you added for your storage.admin role and make sure they are set up correctly. 
2. Create those parent folders manually beforehand if feasible.

**Comment by simonvanderveldt** [comment]
> GCS connector itself in this case won't create nonexistent parent folder, this behavior is consistent with HDFS.

Just to be sure I understand this correctly: Are you saying HDFS will or won't create nonexistent parent directories?

**Comment by hongyegong** [comment]
No, it will not. If you try to write to a HDFS path which doesn't exist it will raise error, I think just as any UNIX like OS would do.

**Comment by simonvanderveldt** [comment]
> No, it will not. If you try to write to a HDFS path which doesn't exist it will raise error, I think just as any UNIX like OS would do.

@hongyegong FYI I don't think this is correct, it was at least not the behavior we were seeing. It was trying to create "paths" on GCS which didn't exist and which it didn't have permissions for.
Didn't/don't have time to look into it further though.
