### ISSUE TITLE
GoogleHadoopFileSystemIntegrationHadoop2Test fails in V1.9.17

### ISSUE THREAD

**Issue by mukund-thakur** [GoogleCloudDataproc/hadoop-connectors#388]
I am trying to use this feature. https://github.com/GoogleCloudDataproc/hadoop-connectors/commit/02b17d1b11369e53a75f48f2ce9e064e040070d9

This contains GoogleHadoopFileSystemIntegrationHadoop2Test , so I tried running it but it fails saying account not valid even though I am able to use my account for listing and updates. 

I can see that this test has been removed from latest version. Could somebody help me running this test as well as make me understand why this class has been removed. Also if this class has been removed, where are the tests for feature "Add Hadoop File System extended attributes support."

Thanks.

**Comment by medb** [comment]
Tests for this feature were moved to a dedicated [GoogleHadoopFileSystemXAttrsIntegrationTest](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/master/gcs/src/test/java/com/google/cloud/hadoop/fs/gcs/GoogleHadoopFileSystemXAttrsIntegrationTest.java) class.

To run integration tests you need to setup authentication for test environment, to do so you can use [run_integration_tests.sh](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/master/tools/run_integration_tests.sh) script, like this:

```bash
tools/run_integration_tests.sh \
  hadoop2 \
  "$PROJECT_ID" \
  "$SERVICE_ACCOUNT_EMAIL" \
  "$PATH_TO_P12_KEY_FILE" \
  -Dit.test=GoogleHadoopFileSystemXAttrsIntegrationTest \
  -DfailIfNoTests=false
```

**Comment by mukund-thakur** [comment]
@medb  Thanks for the command. I tried running this script in Mac OsX but it fails with "readlink: illegal option -- f". Looks like this is a know issue in mac. 
https://github.com/tensorflow/tensorflow/issues/2630 
So I changed the script by manually setting the value of my pk12 file.  Post this the script triggers the test but they fail saying 400 Bad Request 
`{
  "error" : "invalid_grant",
  "error_description" : "Invalid JWT Signature`
although I have used the same credentials to access my buckets using hadoop fs commands and it works fine.

**Comment by medb** [comment]
What credentials did you use? Currently tests support only [`p12` key files](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/master/gcs/CONFIGURATION.md#method-3), but most probably you used [`json` key file](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/master/gcs/CONFIGURATION.md#method-2)?

**Comment by mukund-thakur** [comment]
I am using p12 format only because with json it fails with other errors.

**Comment by medb** [comment]
How did you get create your `p12` file? May you share full command (with redacted sensitive information) how do you use it to run tests?

**Comment by mukund-thakur** [comment]
I created my p12 file using my service account provided by my organisation. 
Here is the full command:
tools/run_integration_tests.sh hadoop3/hadoop2 $PROJECT_ID $SERVICE_ACCOUNT_EMAIL "/Users/mthakur/Downloads/gcp-dev-*.p12"  -Dit.test=GoogleHadoopFileSystemXAttrsIntegrationTest -DfailIfNoTests=false

I am running on version 2.1.2.

**Comment by mukund-thakur** [comment]
Yesterday I cherry picked just the above mentioned commit https://github.com/GoogleCloudDataproc/hadoop-connectors/commit/02b17d1b11369e53a75f48f2ce9e064e040070d9  in my older v1.9.10 and was able to setup the same test GoogleHadoopFileSystemIntegrationHadoop2Test using my Intellij as well. 
This is the full stacktrace I get.

`Caused by: com.google.api.client.auth.oauth2.TokenResponseException: 400 Bad Request
{
  "error" : "invalid_grant",
  "error_description" : "Invalid grant: account not found"
}
	at com.google.api.client.auth.oauth2.TokenResponseException.from(TokenResponseException.java:105)
	at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:287)
	at com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRequest.java:307)
	at com.google.cloud.hadoop.util.CredentialFactory$GoogleCredentialWithRetry.executeRefreshToken(CredentialFactory.java:162)
	at com.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:493)
	at com.google.api.client.auth.oauth2.Credential.intercept(Credential.java:217)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:868)`

**Comment by medb** [comment]
Seems like this is something wrong on your end, because our continuous integration uses the same configuration method to run integration tests and it works.

You need to make sure that `p12` file and other authentication parameters are valid and associated service account has full access to GCS.

**Comment by mukund-thakur** [comment]
I think I have figured out the issue here. Now I am able to run the tests using the same p12 file. 
As per my debugging https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/master/tools/run_integration_tests.sh#L59 expects a link to the actual credentials file not the exact credential file location. 
Example: 
```
./tools/run_integration_tests.sh hadoop3 $PROJECT_ID $SERVICE_ACCOUNT_EMAIL  "file.p12" -DfailIfNoTests=false  
works when file.p12 is pointing to
file.p12 -> /Users/mthakur/Downloads/gcp-dev*.p12
```

```
./tools/run_integration_tests.sh hadoop3 $PROJECT_ID $SERVICE_ACCOUNT_EMAIL  "/Users/mthakur/Downloads/gcp-dev*.p12" -DfailIfNoTests=false
Doesn't work.
```
Also when ran in mac , I have to change readline -f to readline -n.

**Comment by mukund-thakur** [comment]
@medb  Any thoughts on my above comment would be really appreciated.

**Comment by medb** [comment]
From https://github.com/GoogleCloudDataproc/hadoop-connectors/issues/388#issuecomment-635889838 it seems that you find out a solution for your issue. Do you need any further assistance?

**Comment by mukund-thakur** [comment]
> As per my debugging https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/master/tools/run_integration_tests.sh#L59 expects a link to the actual credentials file not the exact credential file location.

Yes. I have found the workaround. Thanks for your assistance.
But isn't this a bug? Expecting a link to the credential file. Won't it be better if the script throws some warning/exception when a link is not present rather than assuming the credentials to be empty and failing later.

**Comment by medb** [comment]
This is a compatibility issue w/ MacOS, not a bug per se because it works on Linux.

MacOS compatibility should be fixed by #398

**Comment by medb** [comment]
Also changed `-f` to `-e` to fail if key file does not exist.

**Comment by mukund-thakur** [comment]
Thanks a lot for taking this up.
