### ISSUE TITLE
Add GCS to Hadoop's core-default?

### ISSUE THREAD

**Issue by ravwojdyla** [GoogleCloudDataproc/hadoop-connectors#513]
We use pyspark to access GCS and use your GCS connector. We have been trying to make it easier to get started with pyspark and GCS, and created [pyspark-gcs](https://github.com/ravwojdyla/pyspark_gcs), it certainly doesn't cover all use cases, but it's a start. In the meantime reported [SPARK-33605](https://issues.apache.org/jira/browse/SPARK-33605), which led to [HADOOP-17402](https://issues.apache.org/jira/browse/HADOOP-17402)? Would you be in favour of adding GCS Hadoop FS implementation to the `core-default` of `hadoop-common`?

**Comment by medb** [comment]
Sure, it would be great to have it there.

Can we in scope of this work include a shaded GCS connector jar in Hadoop distribution so it works out of the box?

**Comment by ravwojdyla** [comment]
@medb great, thanks. Regarding the shaded GCS connector jar, I would suggest to separate these two and potentially open another issue on Hadoop, if you want to pursue that. The reason being that including a GCS connector jar is arguable larger change.
