### ISSUE TITLE
Cancelled vs Ok requests in GCS Metrics

### ISSUE THREAD

**Issue by aharelick** [GoogleCloudDataproc/hadoop-connectors#533]
We use the hadoop connector to interact with GCS from our Dataproc clusters. Recently, while investigating another issue, we noticed a pretty large difference in the amount of data read from our buckets by CANCELLED requests vs OK requests:

<img width="1338" alt="Screen Shot 2021-01-12 at 7 29 56 PM" src="https://user-images.githubusercontent.com/3924168/104403884-60fc9080-550e-11eb-8353-5336a93b4185.png">

From poking around the code it seems like it's not unusual to cancel the request and it might be the main way that streams to GCS are closed?
https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/7891c3d898944c7f47b70fe4e7d276bc4da5c3c1/gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageGrpcReadChannel.java#L448

So, the question is: is it expected behavior to have a significant portion of read volume be from CANCELLED as opposed to OK requests. If so, is this a choice the GCS connector makes or something lower down in Hadoop or the GCS API? If it's not expected does it point to a misconfiguration in our current settings or mean that we should be optimizing something?

I'm also happy to take this up with GCP support, but it seems like there were knowledgeable and responsive maintainers from Google here and the repo may benefit from public questions, thanks!

I believe we're using version hadoop2-1.9.18 of the connector.

**Comment by medb** [comment]
This is an expected GCS connector behavior. `CANCELLED` requests status means that GCS connector issued unbounded request to read data from GCS (from Nth byte to the end of an object) and cancelled/closed this request when necessary portion of the object data (i.e. split) was read.

This is an artifact of the fact that GCS connector does not know how much data Hadoop/Spark/etc want's to read when they open a file and unbounded reads are much faster then bounded, i.e. overhead of sending read request/opening HTTP connection is very high - sending small bounded read data requests is not efficient.

You can control this GCS connector behavior using [Fadvise feature](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/v2.2.0/gcs/CONFIGURATION.md#fadvise-feature-configuration) that by default set to `AUTO`. In `AUTO` Fadvise mode GCS connector initially sends a bounded read request to read 2MiB (configurable), but it it sees that next read call from the Hadoop/Spark/etc is sequential it will send unbounded read request until read pattern will become random (non-sequential) or all necessary data will be read. This is done so GCS connector will have a good performance when reading structured (requires multiple small read requests to read metadata headers first [ORC, Parquet, Avro] and large read after that to read data) and unstructured data (requires one read request to read all data (whole split) at once).

**Comment by aharelick** [comment]
Awesome, that all makes sense to me, thanks!
