### ISSUE TITLE
Add a note that Java 8 is required to build the project (Java 11 breaks the build)

### ISSUE THREAD

**Issue by jaceklaskowski** [GoogleCloudDataproc/hadoop-connectors#536]
I faced a compilation issue using the following command:

```
./mvnw -P hadoop3 clean package
```

It turned out that I used Java 11. Downgrading to Java 8 gave `BUILD SUCCESS`. A line in README.md would make it.

**Comment by medb** [comment]
Added in https://github.com/GoogleCloudDataproc/hadoop-connectors/commit/f662067b7bed95bb33f120e2e9f7ff48443637fd
