### ISSUE TITLE
GoogleHadoopFileSystem should override FileSystem#listStatusIterator() to check path existence

### ISSUE THREAD

**Issue by stiga-huang** [GoogleCloudDataproc/hadoop-connectors#538]
As memtioned in the comments of [FileSystem#listStatusIterator()](https://github.com/apache/hadoop/blob/3101c39b4912b96fbcb7ef05fda2b91cf354f2e9/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java#L2257), it should throw FileNotFoundException if path does not exist:
```java
  /**
   * Returns a remote iterator so that followup calls are made on demand
   * while consuming the entries. Each FileSystem implementation should
   * override this method and provide a more efficient implementation, if
   * possible.
   *
   * Does not guarantee to return the iterator that traverses statuses
   * of the files in a sorted order.
   *
   * @param p target path
   * @return remote iterator
   * @throws FileNotFoundException if <code>p</code> does not exist
   * @throws IOException if any I/O error occurred
   */
  public RemoteIterator<FileStatus> listStatusIterator(final Path p)
  throws FileNotFoundException, IOException {
    return new DirListingIterator<>(p);
  }
```

GoogleHadoopFileSystem and GoogleHadoopFileSystemBase currently don't override this method, which make it return a valid RemoteIterator. The FileNotFoundException is thrown at the first time when RemoteIterator#hasNext() is called.

~~This breaks some applications like (Apache Impala) which assume that FileNotFoundException thrown in RemoteIterator#hasNext() means absence of some subitems (deleted by others concurrently) and it should continue to call hasNext() and next() until hasNext() returns false. It leads Impala come into a dead loop using such a RemoteIterator.~~
(not a good assumption)

AFAIK, HDFS(DistributedFileSystem) and S3(S3AFileSystem) will prefetch some items when constructing the RemoteIterator, which helps to check the existence of the root path. When using GoogleHadoopFileSystem#listStatusIterator(), Impala currently has to do an additional hasNext() call to validate the RemoteIterator before using it. Can we override listStatusIterator() and do this in it?

**Comment by stiga-huang** [comment]
Sorry, we don't need this if the based hadoop version has https://issues.apache.org/jira/browse/HADOOP-16685 (added in hadoop 3.3.0, 3.2.2)

I see the based hadoop3 version is just 3.2.1: https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/5c4fc86a0d548d38da917a8adce21ba30cc6bce7/pom.xml#L104
I think we can simply bump the version to have this.

**Comment by mprashanthsagar** [comment]
Updated Hadoop 3 version to 3.2.2 #549
