### ISSUE TITLE
NPE when trying upload files to GCS in parallel -->  java.lang.NullPointerException: null  : at com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.create(GoogleCloudStorageFileSystem.java:267)

### ISSUE THREAD

**Issue by inmadominguezmira** [GoogleCloudDataproc/hadoop-connectors#561]
Hi
Using the latest hadoop connector for gcs (com.google.cloud.bigdataoss:gcs-connector hadoop3-2.2.0) I'm getting an error when it tries to do a parallel uploading of parquet files to a GCS bucket.
My code creates parquet files in local and , through a copy method, upload it to the GCS " fs.copyFromLocalFile(new Path(FILE_URI_SCHEME + source), new Path(canonizeUri(destination))", 
This is the snippet of  the copy method

```
    @Override
    public void copy(HadoopConfiguration configuration, String source, String destination)
        throws InternalErrorException {
        try (FileSystem fs = getFileSystem(canonizeUri(configuration.getHdfsUri()), configuration)) {
            fs.copyFromLocalFile(new Path(FILE_URI_SCHEME + source), new Path(canonizeUri(destination)));
        } catch (Exception e) {
            String errorMessage = String.format(HdfsOperations.ERROR_COPYING_FILE, HdfsUtil.getFileSystem(destination)) + destination;
            log.error(errorMessage, e);
            throw new InternalErrorException(new TableManagerException(errorMessage, e));
        }
    }
```

the problem appears when there some files in local to copy to GCS in parallel, is the **_FileSystem fs = getFileSystem(canonizeUri(configuration.getHdfsUri()), configuration)_** sentence that throws the exception.
The complete trace of the error is this:

ERROR 2021-05-06T11:40:32.532 com.denodo.vdb.util.hdfs.HdfsOperationsNativeImpl [] - Error copying HDFS files: gs://tests-bucket-multiregion-us/table_testing 
java.lang.NullPointerException: null
		at com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.create(**GoogleCloudStorageFileSystem**.java:267) ~[gcsio.jar:?]
		at com.google.cloud.hadoop.fs.gcs.GoogleHadoopOutputStream.createChannel(GoogleHadoopOutputStream.java:78) ~[gcs-connector.jar:?]
		at com.google.cloud.hadoop.fs.gcs.GoogleHadoopOutputStream.(GoogleHadoopOutputStream.java:70) ~[gcs-connector.jar:?]
		at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.create(GoogleHadoopFileSystemBase.java:598) ~[gcs-connector.jar:?]
		at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1125) ~[hadoop-common.jar:?]

Has something similar happened to someone using this connector? 

Thanks in advance

**Comment by Deependra-Patel** [comment]
Hi @inmadominguezmira, I tried uploading to GCS in parallel with following code and was successful in doing so. In following code, you can see that I create a FileSystem in each thread and use method `copyFromLocalFile` similar to what you are doing.

Could you please more detailed steps for reproducing the above issue?

I would also like to understand your use-case as well. If you just want to upload some local files on a single machine to GCS then using GCS client library would be the right way (https://cloud.google.com/storage/docs/uploading-objects#storage-upload-object-code-sample) or you can use [gsutil](https://cloud.google.com/storage/docs/quickstart-gsutil) if you want to upload using command line. GCS Connector works with hadoop which runs on a cluster and multiple executors (nodes) wants to upload to the GCS bucket.

```java
  class SampleThread extends Thread {

    private final Path outputFile;

    SampleThread(Path outputFile) {
      this.outputFile = outputFile;
    }

    @Override
    public void run() {
      try {
        FileSystem fs = new GoogleHadoopFileSystem();
        fs.initialize(URI.create("gs://deependrap-test"), loadConfig()); // This method is called for loadConfig https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/4b4d659b317e9018852cc43ba2b15930910e5d80/gcs/src/test/java/com/google/cloud/hadoop/fs/gcs/GoogleHadoopFileSystemTestBase.java#L71

        fs.copyFromLocalFile(new Path("/tmp/hello.txt"), outputFile);
        System.out.println("Uploaded file");
        Thread.sleep(10000);
      } catch (IOException | InterruptedException e) {
        e.printStackTrace();
      }
    }
  }

  @Test
  public void testParallelUploads2() throws InterruptedException {
    for (int i=0; i<10; i++) {
      new SampleThread(new Path("outputFileInGCS-"+i)).start();
    }
    // Wait for above threads to finish
    Thread.sleep(20000);
  }
```

**Comment by Deependra-Patel** [comment]
Actually, I am able to reproduce the NPE you mentioned. The key difference was reusing the same FileSystem and call `close`  which would also be happening in your case since you use `try`. 
Also looking at the stacktrace at version (gcs-connector hadoop3-2.2.0) you mentioned, we can see that gs has to be null for NPE https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/42ab6dda6f580288b546d795881969d729cc59d3/gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageFileSystem.java#L267 which is set to null when you call close. 

So the solution for you would be:
1. (**Recommended**) Use GCS java client library to upload
2. Don't close FileSystem
3. Create FileSystem in each thread 

Let us know if you have any other query.


```java
  static class TestRun extends Thread {

    FileSystem fs;
    Path outputFile;

    TestRun(FileSystem fs, Path outputFile) {
      this.fs = fs;
      this.outputFile = outputFile;
    }

    @Override
    public void run() {
      try {
        Random random = new Random();
        int millis = 1000 * random.nextInt(10);
        System.out.println("Sleeping for ms " + millis);
        Thread.sleep(millis);
        fs.copyFromLocalFile(new Path("/tmp/hello.txt"), outputFile);
        fs.close(); // NOTE
        System.out.println("Uploaded file");
      } catch (IOException | InterruptedException e) {
        e.printStackTrace();
      }
    }
  }

  @Test
  public void testParallelUploads_sameFileSystem() throws InterruptedException, IOException {
    FileSystem fs = new GoogleHadoopFileSystem();
    fs.initialize(URI.create("gs://deependrap-test"), loadConfig());

    for (int i=0; i<10; i++) {
      new TestRun(fs, new Path("outputFileInGCS-"+i)).start();
    }
    // Wait for threads to finish
    Thread.sleep(20000);
  }
```
