### ISSUE TITLE
How to impersonate a service account in Spark?

### ISSUE THREAD

**Issue by yujhe** [GoogleCloudDataproc/hadoop-connectors#568]
I had the following configurations in `spark/conf/spark-default.conf`, and it can use the service account in `_credentials.json` to access GCS.

```
spark.hadoop.fs.gs.impl     com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem
spark.hadoop.fs.AbstractFileSystem.gs.impl     com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS
spark.hadoop.google.cloud.auth.service.account.enable     true
spark.hadoop.google.cloud.auth.service.account.json.keyfile     ./_credentials.json
```

Now, I want to impersonate another service account in my Spark job and use it to write files to GCS. How can I do?

I had read [CONFIGURATION.md](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/8e0ec5d7974bc46b760ffb6686c43438d9ffd2db/gcs/CONFIGURATION.md), and set `fs.gs.auth.impersonation.service.account` to the service account I want to impersonate, but it doesn't work.

```scala
spark.sparkContext.hadoopConfiguration.set("fs.gs.auth.impersonation.service.account", "test@myproject.iam.gserviceaccount.com")

(1 to 10).toDF().write.parquet("gs://test/mydir") 
```

**Comment by medb** [comment]
It should work:

https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/9ba13a6d303e8abc23c431283101d96fd148af44/gcs/src/test/java/com/google/cloud/hadoop/fs/gcs/GoogleHadoopFileSystemIntegrationTest.java#L1656-L1674

But you need to make sure that you set all the above properties before initializing `SparkContext`, not just before executing read.
