### ISSUE TITLE
allow setting credentials per bucket in spark

### ISSUE THREAD

**Issue by ruiyang2015** [GoogleCloudDataproc/hadoop-connectors#586]
currently we are setting following globablly in the hadoop config,
"fs.gs.auth.service.account.email" "fs.gs.auth.service.account.private.key.id" "fs.gs.auth.service.account.private.key"

the spark cluster we use is a shared env, so we would like the ability to set the above config for different bucket, 
we have dedicated bucket for each user, and each is provisioned with a different gcs creds. 
at least both s3/azure blob support this kind of fine grained access control, but gcs seems only support setting a global creds instead of a different one per bucket.

**Comment by sid-habu** [comment]
@ruiyang2015 Did you find a solution for this?

**Comment by ruiyang2015** [comment]
> @ruiyang2015 Did you find a solution for this?

nope

**Comment by sid-habu** [comment]
I am running into the same issue where the same Spark session needs to read from a GCS bucket and write to another GCS bucket with a different SA. Are you aware of any workarounds?

**Comment by ruiyang2015** [comment]
> I am running into the same issue where the same Spark session needs to read from a GCS bucket and write to another GCS bucket with a different SA. Are you aware of any workarounds?

nope, unless the owner of the gcs connector to implement this, we are stuck. currently i just write to the same bucket, and then use a gcs python client to copy it to different bucket after spark finish write, less efficient, but that is the best i can think of right now.
