### ISSUE TITLE
https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/master/gcs/INSTALL.md is not up-to-date

### ISSUE THREAD

**Issue by oonisim** [GoogleCloudDataproc/hadoop-connectors#616]
The document is not aligned with the contents with the GCP document and the GitHub issues.

* [Cloud Storage connector ](https://cloud.google.com/dataproc/docs/concepts/connectors/cloud-storage)
* [Clarification about installation with spark #188](https://github.com/GoogleCloudDataproc/hadoop-connectors/issues/188)
* [When writing to BQ run into this error No FileSystem for scheme: gs #206](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/issues/206)

# com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS

This should be com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem

# Hadoop configuration

This statement is incorrect at [Configure Spark](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/master/gcs/INSTALL.md#configure-spark). 

> Note that **you do not need to configure Hadoop** in order to use the GCS connector with Spark.

Do need the configuration.
```
config("spark.hadoop.fs.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem")
```

# Jar files

Need both.

1. spark-bigquery-latest_2.12.jar
2. gcs-connector-hadoop3-2.2.2-shaded.jar'

Only 1 causes ```GoogleHadoopFileSystem``` not found. Only 2 causes ```Failed to find data source: bigquery```.

**Comment by medb** [comment]
Fixed in #180
