### ISSUE TITLE
Workload Identity Federation using account type ExternalAccount is not recognized by GCS connector

### ISSUE THREAD

**Issue by dorg-dakselrod** [GoogleCloudDataproc/hadoop-connectors#671]
I see the latest release notes of the GCS connector mention support for identity federation via accounts of type ExternalAccount but it does not seem to be working with the latest version of the connector. When pointing the connector to my identity json file (which is generated in GCP using Workload Identity Federation) I still receive the error `java.io.IOException: Error reading credentials from stream, 'type' value 'external_account' not recognized. Expecting 'authorized_user' or 'service_account'.` which suggests the connector does not support external accounts.

I'm also unable to find any clear instruction or documentation in this repository for any required configuration-related variables needed to enable workload identity federation. Am I missing some kind of ExternalAccount-specific parameters?

**Comment by GergelyKalmar** [comment]
@medb I'm hitting the same error and that seems to make it impossible to use this connector inside GitHub Actions (https://github.com/google-github-actions/auth in particular). Is there any possible workaround or a rough ETA for when this issue might be fixed?

**Comment by medb** [comment]
GCS connector 3.0.0 with the fix will be released in Q1 2023.

**Comment by GergelyKalmar** [comment]
Sounds good, thank you very much!

**Comment by adrian-vaca-humanes-wt** [comment]
@medb is the approximate release date for 3.0.0 with the fix known?

**Comment by srikanthankamtw** [comment]
@medb currently we are in Q2 2023 could you please give us the approximate date?

**Comment by aburlutskiy** [comment]
@medb @davidrabinowitz could someone provide any ETA when 3.* versions is going to be released?
