### ISSUE TITLE
Recommendations on fs.gs.outputstream.upload.chunk.size

### ISSUE THREAD

**Issue by fabdea95** [GoogleCloudDataproc/hadoop-connectors#694]
Hello,

Users experienced Out of Memory issues when interacting with Google Cloud Storage using DataProc GCS hadoop connector 

The regression occurs when uploading too many objects (mostly small files - ~1MB size files) at the same time (more than 200-300 files) and the root cause of the issue is "fs.gs.outputstream.upload.chunk.size" config key.

The mentioned issue is mitigated by reducing the size of "fs.gs.outputstream.upload.chunk.size" to 256kb, which by default is set to 64 MB [1].
However, reducing this value in all places is probably not ideal, since this can have a performance impact on the uploads and it is definitely not comfortable.

Do you have a list of recommendations for best performance on different scenarios such as many small file uploads, few big file uploads and some other cases? 

Thank you very much for your help; it is highly appreciated

**Comment by medb** [comment]
Recommendations will depend on the specific use case, but there minimal perf impact by reducing `fs.gs.outputstream.upload.chunk.size` to 16 or 32 MiB, going lower then that will slow down file upload, but it depends on the specific application what performance impact it will have.

For your specific use case, setting `fs.gs.outputstream.direct.upload.enable=true` property may be better than reducing upload chunk size to 256 KiB.
