### ISSUE TITLE
Impossible to get basic file(object) info without calling storage.objects.list  api

### ISSUE THREAD

**Issue by IgorBerman** [GoogleCloudDataproc/hadoop-connectors#775]
Since storage.objects.list is class A operation it might be expensive at scale
please provide  api to get basic object info without listing 

the workaround available :
```
FileSystem fs = ..
StorageResourceId resourceId = StorageResourceId.fromUriPath(path.toUri(), true);
((GoogleHadoopFileSystem) fs).getGcsFs().getGcs().getItemInfo(resourceId);
```

**Comment by IgorBerman** [comment]
unfortunately above workaround is not working on dataproc
the problem is that there is no such method,
i.e. instead of 
'com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem.getGcsFs()’

there is 
'com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.getGcsFs()'

**Comment by medb** [comment]
List requests are necessary because of impedance mismatch between object store and FS semantic (i.e. GCS does not have real folders).

You can reduce number of list requests by setting `fs.gs.status.parallel.enable=false` property, but it will reduce performance.
