### ISSUE TITLE
"mapred.bq.temp.gcs.path" error when folder already exists

### ISSUE THREAD

**Issue by lfiaschi** [GoogleCloudDataproc/hadoop-connectors#8]
When the folder corresponding to the parameter `mapred.bq.temp.gcs.path` already exists an exception is thrown 

`java.io.IOException: Conflict occurred creating export directory. Path gs://rocket-omds-cluster-tmp/test7 already exists`

It could be handy to allow the client code to configure overriding of the temp folder or allow using a folder that already exists.

**Comment by Cidan** [comment]
bubbling this up; not being able to overwrite the temp dir on gcs really sucks for automation.

**Comment by jasonjho** [comment]
Any updates on this?
