### ISSUE TITLE
Broken links on maven repository for com.google.cloud.bigdataoss:util

### ISSUE THREAD

**Issue by weiminyu** [GoogleCloudDataproc/hadoop-connectors#800]
Getting "File Not Found" when trying to access 
https://repo.maven.apache.org/maven2/com/google/cloud/bigdataoss/util/2.2.7/util-2.2.7.pom

This is breaking our presubmit test which uses dynamic versioning. Should we wait for this to be fixed or lock dependency to 2.2.6 instead?

Thanks.

**Comment by medb** [comment]
I just checked and https://repo.maven.apache.org/maven2/com/google/cloud/bigdataoss/util/2.2.7/util-2.2.7.pom link works for me, also I can see it when listing artifacts in Maven repo: https://repo.maven.apache.org/maven2/com/google/cloud/bigdataoss/util/2.2.7/

**Comment by Deependra-Patel** [comment]
For posterity, this happened due to issue in Sonatype where publish happened in incosistent state in last release. This was resolved after they did the sync on their side manually. https://issues.sonatype.org/browse/MVNCENTRAL-7456
