### ISSUE TITLE
GCS connectors 2.1.8 and 2.2.7 are not allowing user authentication

### ISSUE THREAD

**Issue by shnapz** [GoogleCloudDataproc/hadoop-connectors#864]
Currently both 2.1.X and 2.2.X GCS connectors are not allowing user accounts to access GCS:

**Issue with 2.1.X**
dependency: "com.google.cloud.bigdataoss:gcs-connector:hadoop3-2.1.8"
when accessing a resource in GCS a browser is opened with:
<img width="483" alt="Screen Shot 2022-08-29 at 9 34 55 AM" src="https://user-images.githubusercontent.com/942930/187300129-c75f0138-70e8-4cf9-bc78-63710a21f202.png">
> The version of the app you're using doesn't include the latest security features to keep you protected. ...

Apparently this is due to Google's deprecation of OAuth OOB flow:
<img width="697" alt="Screen Shot 2022-08-29 at 5 00 48 PM" src="https://user-images.githubusercontent.com/942930/187300345-932f3dd9-1def-41eb-be40-d94c501c25a9.png">

**Issue with 2.2.X**
dependency: "com.google.cloud.bigdataoss:gcs-connector:hadoop3-2.2.7"
As of now branch-2.2.x does not have fs.gs.auth.type and fs.gs.auth.type=USER_CREDENTIALS implemented:
https://github.com/GoogleCloudDataproc/hadoop-connectors/tree/branch-2.2.x

2.2.7 supports only Service Account.

------
This is a blocker for spotify/gcs-tools functionality, new users are not able to access GCS:
[Dependent issue from spotify/gcs-tools repo](https://github.com/spotify/gcs-tools/issues/26)
Apparently the functionality to authenticate user accounts is being implemented in master branch. Do you have any estimation?

**Comment by shnapz** [comment]
Opened in a new issue in "Partner Issue Tracker":
https://partnerissuetracker.corp.google.com/issues/252999627

**Comment by RustedBones** [comment]
Fixed in [v2.1.9](https://github.com/GoogleCloudDataproc/hadoop-connectors/releases/tag/2.1.9) and [2.2.9](https://github.com/GoogleCloudDataproc/hadoop-connectors/releases/tag/2.2.9)

**Comment by medb** [comment]
User credentials authentication will be supported in the upcoming GCS connector 3.0.0 release in Q1 2023: https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/master/gcs/CONFIGURATION.md#user-credentials

**Comment by shnapz** [comment]
@medb do you have any updated estimation of 3.0.0 release?
