### ISSUE TITLE
GCS: How to get rid of or better yet not have _temporary data?

### ISSUE THREAD

**Issue by simonvanderveldt** [GoogleCloudDataproc/hadoop-connectors#868]
When writing data to GCS using the hadoop GCS connector (we're doing so via Spark), a `_temporary` subprefix of the prefix we're writing to is created and all the data is temporarily written there. Once the work has finished the data is moved to the prefix we're writing to and the (data in the) _temporary prefix is deleted.
So for example, the prefix we're writing to is `gs://bucket/prefix/` and the `_temporary` prefix will then be `gs://bucket/prefix/_temporary`.

Now if you have versioning enabled on this bucket you're effectively storing and paying for twice as much data, once as expected for the still active and visible data in `gs://bucket/prefix/` and once for the no longer active and used data in `gs://bucket/prefix/_temporary`. This is obviously undesirable.

AFAIK There's no zero rename committer available for GCS like there is for S3 (see https://spark.apache.org/docs/latest/cloud-integration.html#recommended-settings-for-writing-to-object-stores and https://github.com/steveloughran/zero-rename-committer), so the only other option would be to delete these files automatically, but AFAIK there is no way to include wildcards in the match conditions for bucket lifecycle policies (https://cloud.google.com/storage/docs/lifecycle#matchesprefix-suffix) so there's no way to write a single simple lifecycle policy to delete all the data in all the `_temporary` after let's say a day.

Is there an obvious solution for this (without having to write custom code to walk the tree in the bucket and delete these prefixes)? Is any work possible/planned for a zero rename committer for GCS?

**Comment by medb** [comment]
No, I do not think that there is an existing solution other than cleaning up temp files manually.
