### ISSUE TITLE
Can ServiceAccountJsonKeyFile be ignored when ServiceAccountPrivateKeyId  is set?

### ISSUE THREAD

**Issue by jhsenjaliya** [GoogleCloudDataproc/hadoop-connectors#925]
In version 2.2.9, `CredentialOptions` checks for and requires `ServiceAccountJsonKeyFile` not to be set if ServiceAccountKeyFile, ServiceAccountPrivateKey, ServiceAccountEmail is explicitly set. 

Should there be a priority order or can the ServiceAccountJsonKeyFile be ignored when ServiceAccountPrivateKeyId is set? Or this is expected?

Also some weird thing i notice is that I don't find this `CredentialOptions` class in master branch but i see t in the local jar, which delivers the error: "A JSON key file may not be specified at the same time as credentials via configuration" when this is the case.

**Comment by medb** [comment]
This is expected - to avoid confusion GCS connector checks if only one auth method configured:
https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/81a32da8a79099c044c157b82decebb363dc4fb0/util/src/main/java/com/google/cloud/hadoop/util/CredentialOptions.java#L121-L138

In `master` branch auth/credentials logic were refactored, so `CredentialOptions` class does not exist anymore, instead it's required to explicitly choose an authentication method via `fs.gs.auth.type` property.
