### ISSUE TITLE
Custom implementation of AccessTokenProvider doesn't work according to 2.2.10 documentation.

### ISSUE THREAD

**Issue by akalotkin** [GoogleCloudDataproc/hadoop-connectors#926]
I'm trying to create my own implementation of AccessTokenProvider. It seems there is an issue with contents of util-hadoop jar files  in versions 2.2.9/2.2.10. Jar file contains binaries for version 2.2.8, source code jar file also for version 2.2.8.
See https://repo1.maven.org/maven2/com/google/cloud/bigdataoss/util-hadoop/hadoop3-2.2.10/

Documentation for AccessTokenProvider changed starting from version 2.2.10 (https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/v2.2.10/gcs/CONFIGURATION.md).

Version 2.2.7 works as expected according to documentation (https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/v2.2.7/gcs/CONFIGURATION.md)

**Comment by arunkumarchacko** [comment]
Thank you for reporting this.

There is no change in the behaviour AccessTokenProvider between 2.2.7 and 2.2.10. 

Are you using the source file from the sources files attached to the git release? 

If yes, there is an issue with the source that got attached to the release in Git. 

If not (i.e. if you are taking the dependency from Maven or taking the source from git 2.2.x branch), this should work as expected.

**Comment by akalotkin** [comment]
It looks like tag 2.2.10 was recreated last week. I assume you reverted one of commits. Now I see that 2.2.10 documentation corresponds to whatever source code/binary code available in published jar files. 
Thanks for fixing it.
